/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.imecuadorian.logicgame;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
    }
}
