/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this
 * license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package io.github.imecuadorian.logicgame.views;

import io.github.imecuadorian.logicgame.controller.DeductiveQuestionController;
import io.github.imecuadorian.logicgame.helpers.ShuffleQuestion;
import io.github.imecuadorian.logicgame.model.DeductiveQuestion;
import io.github.imecuadorian.logicgame.services.DeductiveQuestionService;

import java.util.List;

/**
 * @author Hugo Saldarriaga
 */
public class QuestionInductiveView
	extends javax.swing.JDialog {

	/**
	 * Creates new form QuestionView
	 */

	private final DeductiveQuestionController deductiveQuestionController;
	private final List<DeductiveQuestion> questions;
	private final int maxQuestions;

	public QuestionInductiveView(
		java.awt.Frame parent,
		boolean modal,
		DeductiveQuestionService deductiveQuestionService
	) {
		super(parent, modal);
		initComponents();
		this.deductiveQuestionController =
                new DeductiveQuestionController(deductiveQuestionService);
		this.questions = ShuffleQuestion.shuffleQuestions(deductiveQuestionController.getAll());
		this.maxQuestions = deductiveQuestionController.getSize();
		loadQuestion();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        secondPremiseLabel = new javax.swing.JLabel();
        thirdPremiseLabel = new javax.swing.JLabel();
        firstObservation = new javax.swing.JLabel();
        firstOptionRadioButton = new javax.swing.JRadioButton();
        secondOptionRadioButton = new javax.swing.JRadioButton();
        thirdOptionRadioButton = new javax.swing.JRadioButton();
        nextQuestionButton = new javax.swing.JButton();
        icon1 = new javax.swing.JLabel();
        Icons2 = new javax.swing.JLabel();
        icons3 = new javax.swing.JLabel();
        liveLabel2 = new javax.swing.JLabel();
        liveLabel4 = new javax.swing.JLabel();
        liveLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        secondPremiseLabel.setText("jLabel1");

        thirdPremiseLabel.setText("jLabel1");

        firstObservation.setText("jLabel1");

        buttonGroup1.add(firstOptionRadioButton);
        firstOptionRadioButton.setText("jRadioButton1");

        buttonGroup1.add(secondOptionRadioButton);
        secondOptionRadioButton.setText("jRadioButton2");

        buttonGroup1.add(thirdOptionRadioButton);
        thirdOptionRadioButton.setText("jRadioButton3");

        nextQuestionButton.setText("jButton4");
        nextQuestionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextQuestionButtonActionPerformed(evt);
            }
        });

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sol_icon_96px.png"))); // NOI18N

        Icons2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/summer_icon_96px.png"))); // NOI18N

        icons3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sunset_icon_96px.png"))); // NOI18N

        liveLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hearth_icon_50px.png"))); // NOI18N

        liveLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hearth_icon_50px.png"))); // NOI18N

        liveLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hearth_icon_50px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secondPremiseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thirdPremiseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(icon1)
                            .addComponent(Icons2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstOptionRadioButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(secondOptionRadioButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(icons3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(thirdOptionRadioButton)))
                .addContainerGap(666, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(629, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nextQuestionButton)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(liveLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(liveLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(liveLabel3)
                        .addGap(123, 123, 123))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(firstObservation, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(liveLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(liveLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(liveLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)
                        .addComponent(secondPremiseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thirdPremiseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(firstOptionRadioButton)
                        .addGap(78, 78, 78)
                        .addComponent(secondOptionRadioButton)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(icon1)
                        .addGap(18, 18, 18)
                        .addComponent(Icons2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(icons3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(thirdOptionRadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(nextQuestionButton)
                .addGap(53, 53, 53))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(firstObservation, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(720, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void nextQuestionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST
        // :event_nextQuestionButtonActionPerformed
		questions.removeFirst();
		if (questions.isEmpty()) {
			this.dispose();
		} else {
			loadQuestion();
		}
	}                                                  

	private void loadQuestion() {
		DeductiveQuestion question = questions.getFirst();
		firstObservation.setText(question.getFirstPremise());
		secondPremiseLabel.setText(question.getSecondPremise());
		thirdPremiseLabel.setText(question.getConclusion());
		String[] options = ShuffleQuestion.shuffleOptions(question.getOptions()).split(",");
		for (int i = 0; i < options.length; i++) {
			switch (i) {
				case 0:
					firstOptionRadioButton.setText(options[i]);
					break;
				case 1:
					secondOptionRadioButton.setText(options[i]);
					break;
				case 2:
					thirdOptionRadioButton.setText(options[i]);
					break;
			}
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icons2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel firstObservation;
    private javax.swing.JRadioButton firstOptionRadioButton;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icons3;
    private javax.swing.JLabel liveLabel2;
    private javax.swing.JLabel liveLabel3;
    private javax.swing.JLabel liveLabel4;
    private javax.swing.JButton nextQuestionButton;
    private javax.swing.JRadioButton secondOptionRadioButton;
    private javax.swing.JLabel secondPremiseLabel;
    private javax.swing.JRadioButton thirdOptionRadioButton;
    private javax.swing.JLabel thirdPremiseLabel;
    // End of variables declaration//GEN-END:variables
}
